#!/bin/sh

CURDIR=`dirname "$0"`
cd "$CURDIR"
VERSION="1.69"
SOURCE_PACKAGE="leptonica-$VERSION.tar.gz"
EXTRACTED="leptonica-$VERSION"
TARGET_PACKAGE="leptonica-$VERSION-min.tar.gz"
TARGET_DIR="../inc/" # relative to $CURDIR
wget -c http://www.leptonica.com/source/"$SOURCE_PACKAGE"
tar -xzvf "$SOURCE_PACKAGE"
find "$EXTRACTED/prog/" ! -iname 'makefile*' -type f -exec rm -f {} \;
#rm "$SOURCE_PACKAGE"
mkdir "$TARGET_DIR"
tar -czvf "$TARGET_DIR/$TARGET_PACKAGE" "$EXTRACTED"
